### ISSUE TITLE
Makefile not working.

### ISSUE THREAD

**Issue by floodedcodeboy** [matthew-james/esp-vagrant#7]
So I followed your instructions from [here](https://github.com/matthew-james/esp-vagrant/wiki/burning-firmware).

Having built the toolchain as Standalone - then replacing the makefile for the smart config demo with your one I get the following error:

```
$ make
CC user/user_main.c
user/user_main.c:11:21: fatal error: ets_sys.h: No such file or directory
 #include "ets_sys.h"
                     ^
compilation terminated.
make: *** [build/user/user_main.o] Error 1
```

**Comment by matthew-james** [comment]
Can you check the output of ````ls /home/vagrant/esp-open-sdk/sdk/include````?  You should have something like this:

````
[vagrant@vagrant-ubuntu-trusty-64 smart_config]$ ls /home/vagrant/esp-open-sdk/sdk/include
at_custom.h  c_types.h.orig  espconn.h  gpio.h     json   osapi.h    ping.h   smartconfig.h  spi_flash.h  user_interface.h
c_types.h    eagle_soc.h     ets_sys.h  ip_addr.h  mem.h  os_type.h  queue.h  sntp.h         upgrade.h
````

How did you install the SDK?  You don't need to build the toolchain manually anymore; It should be built on provision (when you first run vagrant up) since the commits on April 27th.

**Comment by floodedcodeboy** [comment]
oooh boy you're going to hate me - i already had a vagrant box setup (very similar to yours) however I neglected to use the PATH variables that you setup and that i hadn't symlinked the esptool to the bin folder. sigh. sorry and thanks!
